apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  labels:
    app: nginx-app
    env: dev  
spec:
  containers:
  - name: nginx-app
    image: nginx:latest
    ports:
      - name: nginx-app
        containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-http
spec:
  selector:
    app: nginx-app
  type: NodePort  
  ports:
  - port: 80
    targetPort: 80
